apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gitlab-redis
  namespace: gitlab-system
  labels:
    app.kubernetes.io/name: gitlab-system
    app.kubernetes.io/part-of: gitlab-redis
spec:
  serviceName: gitlab-redis
  selector:
    matchLabels:
      app.kubernetes.io/name: gitlab-system
      app.kubernetes.io/part-of: gitlab-redis
  replicas: 1
  template:
    metadata:
      name: gitlab-redis
      namespace: gitlab-system
      labels:
        app.kubernetes.io/name: gitlab-system
        app.kubernetes.io/part-of: gitlab-redis
    spec:
      containers:
      - name: redis
        image: sameersbn/redis
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-redis
  namespace: gitlab-system
  labels:
    app.kubernetes.io/name: gitlab-system
    app.kubernetes.io/part-of: gitlab-redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: gitlab-system
    app.kubernetes.io/part-of: gitlab-redis
